---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: reload-app-client-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector: 
    matchLabels: 
      web: reload-app-client
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        web: reload-app-client 
    spec: 
      containers: 
      - name: reload-app-client
        image: andresnboza/reload-app-client
        ports: 
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3  
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1      
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: reload-app-client-service 
spec: 
  selector: 
    web: angular
  ports: 
  - port: 80
    targetPort: 80
  type: NodePort 