apiVersion: apps/v1
kind: Deployment
metadata:
  name: reload-app-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reload-app-client
  template:
    metadata:
      labels:
        app: reload-app-client
    spec:
      containers:
      - name: reload-app-client
        image: andresnboza/reload-app-client
        ports:
          - containerPort: 80