---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reload-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reload-server
  template:
    metadata:
      labels:
        app: reload-server
    spec:
      imagePullSecrets:
        - name: aws-registry  
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: reload-server
          image: andresnboza/reload-server
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
          ports:
            - containerPort: 3000
              name: reload-server        
---
apiVersion: v1
kind: Service
metadata:
  name: reload-server
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000
  selector:
    app: reload-server

